-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 09:22:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipos_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_documentos` (
  `id_tdocumento` char(6)  NOT NULL,
  `tipo_documento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tdocumento`))
ENGINE = InnoDB;

insert into tipos_documentos (id_tdocumento,tipo_documento)values(1,'DNI');
insert into tipos_documentos (id_tdocumento,tipo_documento)values(2,'CARNET DE EXTRANGERIA');
insert into tipos_documentos (id_tdocumento,tipo_documento)values(3,'LIBRETA ELECTORAL - 7 DIGITOS');
insert into tipos_documentos (id_tdocumento,tipo_documento)values(4,'LIBRETA ELECTORAL - 7 DIGITOS');
insert into tipos_documentos (id_tdocumento,tipo_documento)values(5,'CARNET DE FUERZAS POLICIALES');
insert into tipos_documentos (id_tdocumento,tipo_documento)values(6,'CARNET DE FUERZAS ARMADAS');
insert into tipos_documentos (id_tdocumento,tipo_documento)values(7,'PASAPORTE');

--procedimiento almacenado para mostrar los tipos de documentos 
DELIMITER $$
create procedure listar_tDocuemento()
BEGIN
SELECT * FROM tipos_documentos;
END

-- -----------------------------------------------------
-- Table `mydb`.`estados_civiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados_civiles` (
  `id_ecivil` char(6)  NOT NULL,
  `estado_civil` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_ecivil`))
ENGINE = InnoDB;


-- INSERTANDO DATOS A LA TABLA DE ESTADOS CIVILES

insert into estados_civiles (id_ecivil,estado_civil)values(1,'SOLTERO');
insert into estados_civiles (id_ecivil,estado_civil)values(2,'CASADO');
insert into estados_civiles (id_ecivil,estado_civil)values(3,'DIVORCIADO');
insert into estados_civiles (id_ecivil,estado_civil)values(4,'VIUDO');


-- procedimiento almacenado para listar estados civile

DELIMITER $$
create procedure listarEstadoCi()
BEGIN
SELECT * FROM estados_civiles;
END

-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `id_persona` CHAR(6) NOT NULl,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NOT NULL,
  `numero_documento` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `direccion` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `id_tdocumento` CHAR(6) NOT NULL,
  `id_ecivil` CHAR(6) NOT NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `dni_UNIQUE` (`numero_documento` ASC),
  INDEX `fk_personas_tipos_documentos1_idx` (`id_tdocumento` ASC),
  INDEX `fk_personas_estados_civiles1_idx` (`id_ecivil` ASC),
  CONSTRAINT `fk_personas_tipos_documentos1`
    FOREIGN KEY (`id_tdocumento`)
    REFERENCES `mydb`.`tipos_documentos` (`id_tdocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_estados_civiles1`
    FOREIGN KEY (`id_ecivil`)
    REFERENCES `mydb`.`estados_civiles` (`id_ecivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



  DELIMITER $$
  DROP PROCEDURE IF EXISTS up_insertar_persona$$
  CREATE PROCEDURE up_insertar_persona
  (
  IN id CHAR(6),
  IN Nombre VARCHAR(100),
  IN Apellido_paterno VARCHAR(50),
  IN Apellido_materno VARCHAR(50),
  IN Numero_documento VARCHAR(20),
  IN Fecha_nacimiento DATE,
  IN Sexo CHAR(1),
  IN Direccion VARCHAR(80),
  IN Telefono VARCHAR(20),
  IN Id_tdocumento char(6) ,
  IN Id_ecivil char(6) 
  )
  BEGIN
  DECLARE contador INT(11);
          SET contador= (SELECT COUNT(*)+1 FROM personas); 
          IF(contador<10)THEN
              SET id= CONCAT('P0000',contador);
          ELSE IF(contador<100) THEN
              SET id= CONCAT('P000',contador);
          ELSE IF(contador<1000)THEN
              SET id= CONCAT('P00',contador);
          ELSE IF(contador<10000)THEN
              SET id= CONCAT('P0',contador);
          ELSE IF(contador<100000)THEN
            SET id= CONCAT('P',contador);
          END IF;
          END IF;        
          END IF;
          END IF;
          END IF; 
      
  insert into personas
  (id_persona,nombre,apellido_paterno,apellido_materno,numero_documento,fecha_nacimiento,sexo,direccion,telefono,id_tdocumento,id_ecivil) 
  values
  (id,Nombre,Apellido_paterno,Apellido_materno,Numero_documento,Fecha_nacimiento,Sexo,Direccion,Telefono,Id_tdocumento,Id_ecivil);
  END

CALL up_insertar_persona(null,'paul','ochoa','sanchez','76574338','1995-01-01','M','jr lima 406','994541220','1','1');



-- -----------------------------------------------------
-- Table `mydb`.`competencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS competencia;

CREATE TABLE IF NOT EXISTS `mydb`.`competencia` (
  `id_competencia` char(7) NOT NULL,
  `nombre_competencia` VARCHAR(150) NULL,
  `numero_co` CHAR(1) NULL,
  PRIMARY KEY (`id_competencia`))
ENGINE = InnoDB;






DELIMITER $$
DROP PROCEDURE IF EXISTS up_insertar_competencia$$
CREATE PROCEDURE  up_insertar_competencia
(
in id char(7),
in Nombre_competencia varchar(150),
in Numero_co char(1)
)
BEGIN
DECLARE contador INT(11);
    
        SET contador= (SELECT COUNT(*)+1 FROM competencia); 
        IF(contador<10)THEN
            SET id= CONCAT('C0000',contador);
        ELSE IF(contador<100) THEN
            SET id= CONCAT('C000',contador);
        ELSE IF(contador<1000)THEN
            SET id= CONCAT('C00',contador);
        ELSE IF(contador<10000)THEN
            SET id= CONCAT('C0',contador);
        ELSE IF(contador<100000)THEN
        SET id= CONCAT('C',contador);
        END IF;
        END IF;        
        END IF;
        END IF;
        END IF; 
    
insert into competencia(id_competencia,nombre_competencia,numero_co) values(id,Nombre_competencia,Numero_co);
END

